// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EditorColorPreview
{
    internal sealed partial class Vsix
    {
        public const string Id = "EditorColorPreview.06059b78-ceae-4188-905d-be8877234e35";
        public const string Name = "Color Preview";
        public const string Description = @"Shows a color preview in front of all named colors, hex, rgb and hsl values in CSS files.";
        public const string Language = "en-US";
        public const string Version = "1.0.1";
        public const string Author = "Mads Kristensen";
        public const string Tags = "color, css, hsl, rgb, hex";
    }
}
